spring:
#  直接访问static目录
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/icedms?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: p@ssw0rd
    type: com.alibaba.druid.pool.DruidDataSource #Druid类型
    druid:
      web-stat-filter: #监控Web
        enabled: true
      stat-view-servlet: #后台页面 http://localhost:8080/druid/login.html
        enabled: true
        login-username: root # 用户名
        login-password: p@ssw0rd # 密码
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 2000
    jedis:
      pool.max-active: 10
      pool.max-idle: 6
      pool.min-idle: 2
    database: 2
  liquibase:
    # 自动跑脚本
    enabled: false
    change-log: classpath:/liquibase/master.xml
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB
      file-size-threshold: 500MB
server:
  port: 8080
logging:
  level:
    com.shih: info
  file:
    path: e:/wwwroot/log1  #日志保存路径
minio:
  endpoint: ${setting.minioServerHost} #Minio服务所在地址
  bucketName: tulaoda #存储桶名称
  accessKey: 1OvzPcDvOey2RVtozHdv #访问的key
  secretKey: lHcEJOzUdjB8v04eOm7airrq7cqlSn7OUanovKDu #访问的秘钥
shiro:
  web:
    enabled: true
  enabled: true


setting:
  documentServer:
    host: http://127.0.0.1:9080
    fileStorageServerHost: http://172.22.240.1:8080
  minioServerHost: http://127.0.0.1:9000
  serverHost: http://host.docker.internal:8080

dingtalk:
  AgentId: 1929550759
  crop_id: dingcc8bab22f32d33d0
  appkey: dingrrcbwultqnvyutli
  appsecret: BDl3Bm_J-oEpX7qIcyNenrfm2qc8GPHj244dt5McXb5rVV3jrFFpftnmS8_kIrms
  aes_key: mjDbijH8qfXWmtbUJdjAetyJdCcweUmMw9k72sPEgmS
  token: apDZfA6QKQUEu3PBYOHqPUXdGJfK