version: '1.0'
name: pipeline-20230905
displayName: pipeline-20230905
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - aa
stages:
  - name: stage-d7e07ef4
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: sc@opensca
        name: open_sca
        displayName: OpenSCA 开源组件检测
        detectPath: ./
        notify: []
        strategy:
          retry: '0'
